### ISSUE TITLE
copying resources failing when dependency is :local/root

### ISSUE THREAD

**Issue by hlolli** [EwenG/badigeon#11]
The only difference between success and failure is that my dependency for libcsound64 is defined with :local/root, I get the following stacktrace. I can bypass this by just uploading to a debug branch on git and test my local commits that way. I guess this could be worth looking into.

```
Exception in thread "main" java.nio.file.AccessDeniedException: target/panaeolus-0.4.0-SNAPSHOT/libcsound64/linux/x86_64/csound/plugins64-6.0
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixCopyFile.copyDirectory(UnixCopyFile.java:141)
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:594)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:254)
	at java.base/java.nio.file.Files.copy(Files.java:1294)
	at badigeon.bundle$pre_visit_directory$fn__2343.invoke(bundle.clj:30)
	at badigeon.bundle$pre_visit_directory.invokeStatic(bundle.clj:29)
	at badigeon.bundle$pre_visit_directory.invoke(bundle.clj:27)
	at badigeon.uberjar$make_directory_file_visitor$reify__2549.preVisitDirectory(uberjar.clj:110)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2731)
	at badigeon.uberjar$copy_directory.invokeStatic(uberjar.clj:127)
	at badigeon.uberjar$copy_directory.invoke(uberjar.clj:120)
	at badigeon.uberjar$copy_dependency.invokeStatic(uberjar.clj:139)
	at badigeon.uberjar$copy_dependency.invoke(uberjar.clj:132)
	at badigeon.uberjar$bundle$fn__2572.invoke(uberjar.clj:174)
	at badigeon.uberjar$bundle.invokeStatic(uberjar.clj:171)
	at badigeon.uberjar$bundle.invoke(uberjar.clj:141)
	at build2$_main.invokeStatic(build2.clj:23)
	at build2$_main.invoke(build2.clj:13)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```

**Comment by EwenG** [comment]
What operating system are you building from ?

**Comment by hlolli** [comment]
this is from linux

**Comment by EwenG** [comment]
Can you check if there is a live process using one of the .so files under the "libcsound64/linux/x86_64/csound/plugins64-6.0" directory ?

**Comment by hlolli** [comment]
I checked again, I delete the target always before compiling and bundling. So I doubt there's some process going there in between. Also in the libcsound64 local directory, I don't think so, there's no java or electron process running which could cause it, I can try restarting and let you know if it works later today. Or alternatively do a minimal reproducible example.

**Comment by EwenG** [comment]
I can't reproduce even with a :local/root dependency on libcsound64.

Can you check that you have read rights on the files in the libcsound64 directory ?
Can you try to manually copy the directory?

```
(java.nio.file.Files/copy
   (java.nio.file.Paths/get "/some/path/libcsound64/linux/x86_64/csound/plugins64-6.0"
                            (into-array String []))
   (java.nio.file.Paths/get "/some/other/path"
                            (into-array String []))
   (into-array
    java.nio.file.StandardCopyOption
    [java.nio.file.StandardCopyOption/COPY_ATTRIBUTES]))
```

**Comment by hlolli** [comment]
that seems to work

```
(java.nio.file.Files/copy
 (java.nio.file.Paths/get "/home/hlolli/panaeolus/libcsound64/native/libcsound64/linux/x86_64/csound/plugins64-6.0"
                          (into-array String []))
 (java.nio.file.Paths/get "/home/hlolli/panaeolus/deleteme"
  (into-array String []))
 (into-array
  java.nio.file.StandardCopyOption
  [java.nio.file.StandardCopyOption/COPY_ATTRIBUTES]))
#object[sun.nio.fs.UnixPath 0x33abde31 "/home/hlolli/panaeolus/deleteme"]
user=> 
```

**Comment by hlolli** [comment]
also

```
(java.nio.file.Files/copy
 (java.nio.file.Paths/get "/home/hlolli/panaeolus/libcsound64/native/libcsound64/linux/x86_64/csound/plugins64-6.0/libwidgets.so"
                          (into-array String []))
 (java.nio.file.Paths/get "/home/hlolli/panaeolus/deleteme.so"
  (into-array String []))
 (into-array
  java.nio.file.StandardCopyOption
  [java.nio.file.StandardCopyOption/COPY_ATTRIBUTES]))
```

but when I delete that file

```
-r-xr-xr-x  1 hlolli users 208K Jul  1 10:16 deleteme.so
```

I actually think I know now the problem

it's originally copied from a write protected directory, and I've yet to push the latest changes, so you don't get the error :P

I'm 99,9% sure now that this just on my side

**Comment by hlolli** [comment]
Or alternatively, some file permission settings are more strict in badigeon than is allowerd from that Files/copy example?

**Comment by EwenG** [comment]
The error message implies that the error is during the writing, not the reading, so a write protected directory is a plausible cause of the problem.

The permission settings in badigeon are exactly like in the example.

**Comment by hlolli** [comment]
chmod +rw fixed it, closing, thanks for looking at it (going to test the windows fix later tonight too!)
