### ISSUE TITLE
Help with strange behaviour

### ISSUE THREAD

**Issue by hlolli** [EwenG/badigeon#12]
Still I'm struggling with panaeolus, this time on Windows (and this bug was there since some time but only causes problems on runtime)

In short, I define either the newest version of clojure.core/async in deps.edn or the newest git, somehow an ancient version of clojure.core/async gets bundled.

Given the following `clojure -Stree`

```
org.clojure/clojure 1.10.0
  org.clojure/core.specs.alpha 0.2.44
  org.clojure/spec.alpha 0.2.176
expound/expound 0.7.2
com.google.inject/guice 4.2.2
  javax.inject/javax.inject 1
  com.google.guava/guava 25.1-android
    com.google.errorprone/error_prone_annotations 2.1.3
    org.codehaus.mojo/animal-sniffer-annotations 1.14
    org.checkerframework/checker-compat-qual 2.0.0
    com.google.j2objc/j2objc-annotations 1.1
    com.google.code.findbugs/jsr305 3.0.2
  aopalliance/aopalliance 1.0
rksm/subprocess 0.1.3
overtone/ableton-link 1.0.0-beta11
  commons-io/commons-io 2.6
  org.clojure/data.priority-map 0.0.9
techascent/tech.jna 3.18
  org.clojure/tools.logging 0.4.1
  techascent/tech.resource 4.5
panaeolus/libcsound64 https://github.com/panaeolus/libcsound64.git 9d9625d
  cpath-clj/cpath-clj 0.1.2
    org.clojure/java.classpath 0.2.2
  jack2/jack2 https://github.com/panaeolus/jack2.git e5d454e
com.kunstmusik/CsoundJNA 1.0.1
  net.java.dev.jna/jna-platform 5.3.0
instaparse/instaparse 1.4.9
net.java.dev.jna/jna 5.3.1
nrepl/nrepl 0.6.0
badigeon/badigeon https://github.com/EwenG/badigeon.git 1e28b19
  org.clojure/tools.deps.alpha 0.7.516
    org.springframework.build/aws-maven 5.0.0.RELEASE
    org.clojure/tools.cli 0.3.5
    org.apache.maven.resolver/maven-resolver-transport-wagon 1.1.1
      org.apache.maven.wagon/wagon-provider-api 3.0.0
    org.apache.maven.resolver/maven-resolver-transport-http 1.1.1
      org.slf4j/jcl-over-slf4j 1.7.25
        org.slf4j/slf4j-api 1.7.25
      org.apache.httpcomponents/httpcore 4.4.8
      org.apache.httpcomponents/httpclient 4.5.4
        commons-codec/commons-codec 1.10
    org.apache.maven.resolver/maven-resolver-transport-file 1.1.1
    org.apache.maven/maven-core 3.5.2
      org.codehaus.plexus/plexus-component-annotations 1.7.1
      org.eclipse.sisu/org.eclipse.sisu.plexus 0.3.3
        javax.enterprise/cdi-api 1.0
          javax.annotation/jsr250-api 1.0
      org.apache.maven/maven-settings-builder 3.5.2
        org.sonatype.plexus/plexus-sec-dispatcher 1.4
          org.sonatype.plexus/plexus-cipher 1.4
      org.apache.maven/maven-settings 3.5.2
      org.apache.maven.shared/maven-shared-utils 3.1.0
      org.codehaus.plexus/plexus-classworlds 2.5.2
      com.google.inject/guice$no_aop 4.0
      org.eclipse.sisu/org.eclipse.sisu.inject 0.3.3
      org.apache.maven/maven-builder-support 3.5.2
      org.apache.maven/maven-plugin-api 3.5.2
      org.apache.maven/maven-artifact 3.5.2
    org.apache.maven.resolver/maven-resolver-api 1.1.1
    org.apache.maven/maven-resolver-provider 3.5.2
      org.apache.commons/commons-lang3 3.5
      org.apache.maven/maven-model-builder 3.5.2
        org.codehaus.plexus/plexus-interpolation 1.24
      org.codehaus.plexus/plexus-utils 3.1.0
      org.apache.maven/maven-model 3.5.2
      org.apache.maven/maven-repository-metadata 3.5.2
    org.clojure/data.xml 0.2.0-alpha5
      org.clojure/data.codec 0.1.0
    org.apache.maven.resolver/maven-resolver-spi 1.1.1
    org.slf4j/slf4j-nop 1.6.2
    s3-wagon-private/s3-wagon-private 1.3.1
      com.fasterxml.jackson.core/jackson-databind 2.5.5
        com.fasterxml.jackson.core/jackson-annotations 2.5.0
      com.fasterxml.jackson.core/jackson-core 2.5.5
      com.amazonaws/aws-java-sdk-s3 1.11.184
        com.amazonaws/jmespath-java 1.11.184
        com.amazonaws/aws-java-sdk-core 1.11.184
          joda-time/joda-time 2.8.1
          com.fasterxml.jackson.dataformat/jackson-dataformat-cbor 2.6.7
          software.amazon.ion/ion-java 1.0.2
          commons-logging/commons-logging 1.1.3
        com.amazonaws/aws-java-sdk-kms 1.11.184
    org.clojure/tools.gitlibs 0.2.64
      com.jcraft/jsch.agentproxy.jsch 0.0.9
      org.eclipse.jgit/org.eclipse.jgit 4.10.0.201712302008-r
        com.googlecode.javaewah/JavaEWAH 1.1.6
        com.jcraft/jsch 0.1.54
      com.jcraft/jsch.agentproxy.connector-factory 0.0.9
        com.jcraft/jsch.agentproxy.sshagent 0.0.9
        com.jcraft/jsch.agentproxy.usocket-jna 0.0.9
        com.jcraft/jsch.agentproxy.pageant 0.0.9
        com.jcraft/jsch.agentproxy.core 0.0.9
        com.jcraft/jsch.agentproxy.usocket-nc 0.0.9
    org.apache.maven.resolver/maven-resolver-connector-basic 1.1.1
    org.apache.maven.resolver/maven-resolver-impl 1.1.1
    org.apache.maven.resolver/maven-resolver-util 1.1.1
org.jaudiolibs/jnajack 1.3.0
org.clojure/core.async https://github.com/clojure/core.async.git 300d6e1
  org.clojure/tools.analyzer.jvm 0.7.2
    org.clojure/tools.analyzer 0.6.9
    org.clojure/tools.reader 1.0.0-beta4
    org.clojure/core.memoize 0.5.9
      org.clojure/core.cache 0.6.5
    org.ow2.asm/asm-all 4.2
```

It's clear that I have here the latest git defined.

But when I run the jar I get
```
Syntax error macroexpanding clojure.core/refer-clojure at (clojure/core/async.clj:9:1)
 clojure.lang.ExceptionInfo: Call to clojure.core/refer-clojure did not conform to spec
```

This is from a very old core.async namespace, then if I clean `C:\Users\User\.m2\repository\org\clojure\core.async` and run build2.clj (bundle script) I see this

```
> $env:COMPILING_PANAEOLUS = '1'; clojure -A:jar -m build2
Could not find any internals in C:\Users\User\AppData\Roaming\panaeolus\Cache\csound-6.13/jack!
Could not find any internals in driver directory!
`default' server already active
Failed to open server
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
Drivers/internals found in : C:\Users\User\AppData\Roaming\panaeolus\Cache\csound-6.13
Drivers/internals found in : C:\Users\User\AppData\Roaming\panaeolus\Cache\csound-6.13
Downloading: org/clojure/core.async/0.1.346.0-17112a-alpha/core.async-0.1.346.0-17112a-alpha.pom from https://repo1.maven.org/maven2/
Downloading: org/clojure/core.async/0.1.346.0-17112a-alpha/core.async-0.1.346.0-17112a-alpha.jar from https://repo1.maven.org/maven2/
```

I already tried deleting .cpcache, but I have no clue where that core.async 0.1.346.0 is defined, it does not appear on the classpath from `clojure -Spath`. Do you know what could cause this?

**Comment by hlolli** [comment]
Ah I just solved it
```
  (uberjar/bundle (str "target/panaeolus-" +version+)
                  {:exclude-libs '#{clojure.core/async}
				  :deps-map (-> (deps-reader/slurp-deps "deps.edn")
                                 (assoc :paths ["target/classes" "resources"])
                                 (update :deps dissoc 'badigeon/badigeon))})
```
instead of dissoc-ing clojure.core/asinc I exclude it, it just can't be both. This was after 2 hour of trial and error, and had tried everything except this combination :P

**Comment by hlolli** [comment]
Sorry for the spam, but again, runtime, it doesn't work, an old error message I've known from the past

```
error:  Exception in thread "async-dispatch-2"
error:  java.lang.IllegalArgumentException: No implementation of method: :blockable? of protocol: #'clojure.core.async.impl.protocols/Handler found for class: clojure.core.async.impl.ioc_macros$fn_handler$reify__6328
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:581)
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
        at clojure.core.async.impl.protocols$eval9370$fn__9371$G__9357__9376.invoke(protocols.clj:25)
        at clojure.core.async.impl.channels.ManyToManyChannel.take_BANG_(channels.clj:234)
        at clojure.core.async.impl.protocols$eval9267$fn__9268$G__9259__9271.invoke(protocols.clj:15)
        at clojure.core.async.impl.protocols$eval9267$fn__9268$G__9258__9275.invoke(protocols.clj:15)
        at clojure.core.async.impl.ioc_macros$take_BANG_.invokeStatic(ioc_macros.clj:983)
        at panaeolus.csound.csound_jna$debounce$fn__10694$state_machine__6315__auto____10703$fn__10705.invoke(csound_jna.clj:28)
        at panaeolus.csound.csound_jna$debounce$fn__10694$state_machine__6315__auto____10703.invoke(csound_jna.clj:28)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:975)
        at panaeolus.csound.csound_jna$debounce$fn__10694.invoke(csound_jna.clj:28)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

error:  Exception in thread "async-dispatch-4"
error:  java.lang.IllegalArgumentException: No implementation of method: :blockable? of protocol: #'clojure.core.async.impl.protocols/Handler found for class: clojure.core.async.impl.ioc_macros$fn_handler$reify__6328
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:581)
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
        at clojure.core.async.impl.protocols$eval9370$fn__9371$G__9357__9376.invoke(protocols.clj:25)
        at clojure.core.async.impl.channels.ManyToManyChannel.take_BANG_(channels.clj:234)
        at clojure.core.async.impl.protocols$eval9267$fn__9268$G__9259__9271.invoke(protocols.clj:15)
        at clojure.core.async.impl.protocols$eval9267$fn__9268$G__9258__9275.invoke(protocols.clj:15)
        at clojure.core.async.impl.ioc_macros$take_BANG_.invokeStatic(ioc_macros.clj:983)
        at panaeolus.csound.pattern_control$csound_make_instance$fn__12911$state_machine__6315__auto____12936$fn__12938.invoke(pattern_control.clj:103)
        at panaeolus.csound.pattern_control$csound_make_instance$fn__12911$state_machine__6315__auto____12936.invoke(pattern_control.clj:103)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:975)
        at panaeolus.csound.pattern_control$csound_make_instance$fn__12911.invoke(pattern_control.clj:103)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

error:  Exception in thread "clojure.core.async.timers/timeout-daemon"
error:  java.lang.ClassCastException: clojure.core.async.impl.timers.TimeoutQueueEntry cannot be cast to clojure.core.async.impl.timers.TimeoutQueueEntry
        at clojure.core.async.impl.timers$timeout_worker.invokeStatic(timers.clj:48)
        at clojure.core.async.impl.timers$timeout_worker.invoke(timers.clj:43)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Unknown Source)

error:  Exception in thread "async-dispatch-5" java.lang.IllegalArgumentException: No implementation of method: :blockable? of protocol: #'clojure.core.async.impl.protocols/Handler found for class: clojure.core.async.impl.ioc_macros$fn_handler$reify__6328
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:581)
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
        at clojure.core.async.impl.protocols$eval9370$fn__9371$G__9357__9376.invoke(protocols.clj:25)
        at clojure.core.async.impl.channels.ManyToManyChannel.take_BANG_(channels.clj:234)
        at clojure.core.async.impl.protocols$eval9267$fn__9268$G__9259__9271.invoke(protocols.clj:15)
        at clojure.core.async.impl.protocols$eval9267$fn__9268$G__9258__9275.invoke(protocols.clj:15)
        at clojure.core.async.impl.ioc_macros$take_BANG_.invokeStatic(ioc_macros.clj:983)
        at panaeolus.csound.pattern_control$csound_pattern_control$fn__13929$fn__14017$state_machine__6315__auto____14062$fn__14064.invoke(pattern_control.clj:394)
        at panaeolus.csound.pattern_control$csound_pattern_control$fn__13929$fn__14017$state_machine__6315__auto____14062.invoke(pattern_control.clj:394)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:975)
        at panaeolus.csound.pattern_control$csound_pattern_control$fn__13929$fn__14017.invoke(pattern_control.clj:394)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

error:  Exception in thread "async-dispatch-6"
error:  java.lang.IllegalArgumentException: No implementation of method: :blockable? of protocol: #'clojure.core.async.impl.protocols/Handler found for class: clojure.core.async.impl.ioc_macros$fn_handler$reify__6328
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:581)
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
        at clojure.core.async.impl.protocols$eval9370$fn__9371$G__9357__9376.invoke(protocols.clj:25)
        at clojure.core.async.impl.channels.ManyToManyChannel.take_BANG_(channels.clj:234)
        at clojure.core.async.impl.protocols$eval9267$fn__9268$G__9259__9271.invoke(protocols.clj:15)
        at clojure.core.async.impl.protocols$eval9267$fn__9268$G__9258__9275.invoke(protocols.clj:15)
        at clojure.core.async.impl.ioc_macros$take_BANG_.invokeStatic(ioc_macros.clj:983)
        at panaeolus.event_loop$csound_event_loop_thread$fn__11226$state_machine__6315__auto____11243$fn__11245.invoke(event_loop.clj:75)
        at panaeolus.event_loop$csound_event_loop_thread$fn__11226$state_machine__6315__auto____11243.invoke(event_loop.clj:75)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:975)
        at panaeolus.event_loop$csound_event_loop_thread$fn__11226.invoke(event_loop.clj:75)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by EwenG** [comment]
The correct bundle option is ":excluded-libs" instead of ":exclude-libs". Also excluding core.async or not does not seem to make a difference in your case.
Disabling direct-linking seems to solve the error so I would tend to think that it is an issue with core.async when compiling with direct-linking.

**Comment by hlolli** [comment]
I asked about this last week on the #core-async slack channel, and it was pointed out that it must be because of double compilation or double evaluation. I believed I got it working before I fixed the jar problem on windows, by just dissocing it from the bundle. Still leaves the question as to why that ancient core.async version is downloaded with no core.async in the dep-tree.

But you are right, disabling direct linking fixes this problem, I hope that wont cause too much performance loss (I guess it's then just as fast as if I was running clojure from a repl).

Thanks for your help!

**Comment by EwenG** [comment]
Ok I think I found the issue:

:exclude-libs '#{clojure.core/async}
should be
:excluded-libs '#{org.clojure/core.async}

Not sure why it does not work when the .clj files are there though. In theory the Clojure compiler should peek .class files over .clj ones

**Comment by EwenG** [comment]
The real issue was that I forgot to set the last modified time on zip entries, thus changing the order the clojure compiler loads files. This is fixed on master.
You don't need to exclude "org.clojure/core.async" anymore, although excluding it will make the jar smaller.

**Comment by hlolli** [comment]
genius, we are smashing those bugs :P

I'll try later today!

**Comment by hlolli** [comment]
This works, all running smoothly!
