### ISSUE TITLE
possible bug when copying conflict classes

### ISSUE THREAD

**Issue by mikeananev** [EwenG/badigeon#20]
Hello.

I made a clj-new project template based on badigeon https://github.com/mikeananev/sapp
Using this template to build big project I've encountered an error during the uberjar building.
To reproduce problem I created simple project https://github.com/mikeananev/bugapp.
This project uses two building tools: cambada and badigeon. 
If you look inside uberjar produced by cambada then you will see much more classes in folder org/objectweb/asm. in Badigeon version of uberjar folder org/objectweb/asm has a few of them.
I can't detect the place where badigeon ignores classes and not copy them.

Steps to reproduce problem:
0. clone the project https://github.com/mikeananev/bugapp

1. If I build uberjar using cambada and run uberjar, then everything works fine.

> clj -A:build
> java -jar target/app-0.1.0-standalone.jar
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
system started.

2. But if I use badigeon then not all classes are copied into uberjar.

> clj -R:bg -A:uberjar
>java -jar target/app-0.1.0-SNAPSHOT-standalone.jar
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.tools.analyzer.passes.jvm.validate_loop_locals$loading__6721__auto____2293.invoke(validate_loop_locals.clj:9)
	at clojure.tools.analyzer.passes.jvm.validate_loop_locals__init.load(Unknown Source)
	at clojure.tools.analyzer.passes.jvm.validate_loop_locals__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5989)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.tools.analyzer.passes.jvm.warn_on_reflection$loading__6721__auto____2291.invoke(warn_on_reflection.clj:9)
	at clojure.tools.analyzer.passes.jvm.warn_on_reflection__init.load(Unknown Source)
	at clojure.tools.analyzer.passes.jvm.warn_on_reflection__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core.async.impl.ioc_macros$loading__6721__auto____1691.invoke(ioc_macros.clj:12)
	at clojure.core.async.impl.ioc_macros__init.load(Unknown Source)
	at clojure.core.async.impl.ioc_macros__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core.async$loading__6721__auto____1221.invoke(async.clj:9)
	at clojure.core.async__init.load(Unknown Source)
	at clojure.core.async__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at taoensso.sente$loading__6721__auto____1219.invoke(sente.cljc:1)
	at taoensso.sente__init.load(Unknown Source)
	at taoensso.sente__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at qwerty.app.websocket$loading__6721__auto____151.invoke(websocket.clj:1)
	at qwerty.app.websocket__init.load(Unknown Source)
	at qwerty.app.websocket__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)

	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6780.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at qwerty.app.core$loading__6721__auto____149.invoke(core.clj:1)
	at qwerty.app.core__init.load(Unknown Source)
	at qwerty.app.core__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForName(RT.java:2220)
	at clojure.lang.RT.loadClassForName(RT.java:2239)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6839.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.lang.Util.loadWithClass(Util.java:251)
	at qwerty.app.core.<clinit>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.Type
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:416)
	at clojure.lang.RT.classForName(RT.java:2211)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2224)
	at clojure.tools.analyzer.jvm.utils$loading__6721__auto____2295.invoke(utils.clj:9)
	at clojure.tools.analyzer.jvm.utils__init.load(Unknown Source)
	at clojure.tools.analyzer.jvm.utils__init.<clinit>(Unknown Source)
	... 196 more

**Comment by mikeananev** [comment]
clj deps cli and clj-new are latest versions

**Comment by mikeananev** [comment]
i've tried to use (uberjar/merge-resource-conflicts out-path) but it doesn't help.

**Comment by mikeananev** [comment]
ok, i've solved problem for myself. 
The key line is 198 in badigeon.uberjar -> binding [*resource-conflict-paths* resource-conflict-paths]. If there is no binding (e.g. binding []) then classes will be overwritten and it works for me. 

I think it would be great to have turn off/on parameter for this binding for class overwrite.
Also it is more convenient to see what class has duplications in different jars. So here is a code, that shows duplications with jar names. Then I can detect via clj -Stree what jar to exclude 

(defn find-res-conflicts
  ([]
   (find-res-conflicts {:deps-map (deps-reader/slurp-deps "deps.edn")}))
  ([{:keys [deps-map aliases] :as params}]
   (let [res-conflicts        (#'badigeon.uberjar/find-resource-conflicts* params)
         class-conflict-struc (mapv (fn [e] (when (str/ends-with? (key e) ".class")
                                              {:class (key e)
                                               :jars  (vec (sort (map #(.getName %) (val e))))}))
                                res-conflicts)]
     (remove nil? class-conflict-struc))))

**Comment by EwenG** [comment]
Thank you for the report !
I will have a look

**Comment by EwenG** [comment]
I pushed a change to master. ".class" files are now always copied to the output bundle. Badigeon will still warn on when duplicate ".class" files are found though.
As you suggested, I will probably update the find-resource-conflicts function to also return the path of the jars containing the duplicate classes. As you already found out, this is already almost what the private find-resource-conflicts* function does.

**Comment by mikeananev** [comment]
Thank you!

**Comment by mikeananev** [comment]
I closed the issue and will remove repo with buggy app demo.

**Comment by EwenG** [comment]
find-resource-conflicts now returns the directories or jar files containing the conflicting resources

**Comment by borkdude** [comment]
I'm getting errors about duplicate `.DS_Store` files on macOS:

```
[{:type clojure.lang.ExceptionInfo,
    :message "Duplicate path",
    :data
    {:from "resources/.DS_Store",
     :to "deploy/prod/target/target_src",
     :relative-path ".DS_Store"},
    :at
    [badigeon.bundle$make_directory_file_visitor$reify__1427
     visitFile
     "bundle.clj"
     51]}],
```

How do I exclude them from the build?
